//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        public int id { get; set; }
        [Required(ErrorMessage = "You can't leave this empty.")]
        [RegularExpression(@"^[a-zA-Z0-9 ]+$", ErrorMessage = "Please enter a valid name.")]
        public string name { get; set; }
        [Required(ErrorMessage = "You can't leave this empty.")]
        [StringLength(15, MinimumLength = 6, ErrorMessage = "Minimum 6 Characters.")]
        public string password { get; set; }
    }
}
