//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Drink
    {
        public int id { get; set; }

        //[Required(ErrorMessage = "Image is required")]
        //[Display(Name ="Image")]
        public string Dimg { get; set; }

        [Required(ErrorMessage = "Drink Name is required")]
        [Display(Name = "Drink Name")]
        [DataType(DataType.Text)]
        public string Dname { get; set; }

        [Required(ErrorMessage = "Drink Price is required")]
        [Display(Name = "Drink Price")]
        [RegularExpression(@"[+-]?(?=\.\d|\d)(?:\d+)?(?:\.?\d*)(?:[eE][+-]?\d+)?", ErrorMessage = "Inter Prince")]
        public Nullable<double> Dprice { get; set; }
    }
}
